sudo: required

language: generic

services:
  - docker

before_install:
  - echo "start creating an image with dockerfile"
  - docker build -t chcjswo/docker-react-app -f Dockerfile.dev .

script:
  - docker run -e CI=true chcjswo/docker-react-app npm run test -- --coverage

after_success:
  - echo "test success"

  deploy:
    provider: elastickbeanstalk
    region: "ap-northeast-2"
    app: "docker-react-app"
    env: "DockerReactApp-env"
    bucket_name: ""
    bucket_path: "docker-react-app"
    on:
      baranch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY